script: bash ./deploy.sh
sudo: false
addons:
  apt:
    packages:
      - python-pip
env:
  global:
    - GH_REF: github.com/garaemon/beginner-tips.git
    - secure: "gYxWgfuUNXzEybxSPSvbRaUA5KZLSRCftY3cugG1vkLfRvxolkf2izZqAkgFFFwM3OZ4lBOVyT8sxz2f22o81HY6XVbLhUsvk9Y+WvtV32mr1bG4myfDEwz8ALglKd5YWLF0gQnQRQxljD7LhwZr9LBpi0cGdfhqyW5WtvCNMvTtJbyskfD0JNJwVxGxI/d91/5PYdxYSyYmDcYusyAP7YNUs7fBWihlK60/rxTvXPM8Ur+jEobDfmL5hMDW7ydaLCoSuBAfT8ApQMFjVQnSSZpruCXPW9vlvzbZhNMec21iH3W8NpDRo48koE8p4PVie5/wHusF8C9u5VSXsnlQMeiAM/kxSN64YQIFopnsIR+yn39Hmjj+h8qQ8ur/oxZiVBuDeE9us3BoV52UcLB00ImoL5nJ3EoYKYDAfosSFJJ7bKpFPox+T2N/GTfHI3LXHUMfCqCoYYanYw+XXKMExsGXXPUzxUzYpNPvaov/ycKvhbhAu9zEeE1UL8wesPvdpD+n/FSOAjTN+K6sjjFE3PAzafis2MyQogVHfi+V124LUB3mo7pLUhxzI2gMmE9Ozbi4le7g9d/xvn/6za4o0rTf/pmqXxtJXLd+G32nXrxEjjtzuDRUoSMY0aehMEuvZE5xg/qLmkkFtm+6jjnHQxiJdMf7oLhJAqmFY9lYm7I="
