script: bash ./deploy.sh
sudo: false
language: python
cache: pip
addons:
  apt:
    packages:
      - python-pip
env:
  global:
    - GH_REF: github.com/garaemon/beginner-tips.git
    - secure: "cQrakXzrxt03dIvDeClUNFyE+mmvQDIoTg83AwSyc2E5rB3cKfrF3mv8BjbKGPVxvgb811E8+70clopCokumgL4qCVaXc5ehdKw7lYINGY3+j5/p6H7vDVlgoqTzUJgDaeg6f0WGEOKy/Qvt2su/DShjaFkjz+6vSV3l6CCwDKMm5/OjfoUvtL9AE0zgVnGNVu5Lray13Kku2ecucyGZTd9RT4lKWyyoPMO1dulzeUkitO5+UoFRArZ4Z+4Txt1qeKwj0rwzW/WHM0Gy0yHmogYe16MjQDrTTcqR6qq9eK5RinXhyf1aAM5jDvTTHuEhMiJr2lImYrxS2wRbgVf9DHsI6zOXMAcuvlAsbxKNdNMiyssqZuvyuacMDkMCDuqnCYUibjzQB1KwG5BJt7xZ1QE412NvnDtQ0Zc542XOqw4lYRFkWnFzTG42zCiczeZAoWr1n3t5SGXQv4kkDvDLBwaQ3x25/SuCtu3E8sXXFRpwj+l4gLPNxvReZOTRx1kuFnqL61pj+v28EoAHIh3waF35gm/ey0qheGrycrYqzvLGsMMD81ZKATdJITfcXn0Ysw6PSDqDMuyno9eH+tCDtZab3RubXqVfEdy/u1accP5tQiFQq2QtO0hn9HWitHCF1qBTGmob2+m7WBA1BdUX0zyKjwhmf6DDO4cHBHlAXNw="
